name: vchat
description: A Internet Messaging/Chatting App with Multi-layered Encryption/Decryption Architecture based on Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  flutter_icons: ^1.1.0
  intl: ^0.16.1
  shared_preferences: ^0.5.8
  flutter_staggered_grid_view: ^0.3.0
  provider: ^4.3.0
  tuple: ^1.0.3
  encrypt: ^4.1.0
  modal_progress_hud: ^0.1.3
  firebase_core: any
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.4+1
  firebase_storage: ^4.0.0
  flushbar: ^1.10.4
  image_picker: ^0.6.7+7
  image_cropper: ^1.3.0
  flutter_local_notifications: ^1.4.4+4
  path_provider: ^1.6.14
  md2_tab_indicator: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
